const SUPABASE_URL='https://dvpxlirjmyluwljivtdw.supabase.co';
const FUNCTION_URL=`${SUPABASE_URL}/functions/v1/wallet-auth-v2`;
const $=id=>document.getElementById(id),toast=$('toast'),authShell=$('authShell'),setupShell=$('setupShell'),dashboardShell=$('dashboardShell'),authStatus=$('authStatus');
const FIRST_LESSON='3b3bf017-df1f-401c-8716-36b07ff32706';
let wallet=null,profile=null,journeyState={progress:[],traits:[]};
const message=(text,error=false)=>{if(authStatus){authStatus.textContent=text;authStatus.className=`auth-status ${error?'error':''}`}if(toast){toast.textContent=text;toast.classList.add('show');clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>toast.classList.remove('show'),3500)}};
function showOnly(s){[authShell,setupShell,dashboardShell].forEach(x=>x?.classList.add('hidden'));s?.classList.remove('hidden')}
function short(a){return a?`${a.slice(0,4)}…${a.slice(-4)}`:'Connect wallet'}
function provider(){return window.solflare?.isSolflare?window.solflare:(window.phantom?.solana||window.solana||null)}
async function api(body){const r=await fetch(FUNCTION_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(j.error||'Wallet authentication failed');return j}
async function signChallenge(scope='login'){const c=await api({action:'challenge',walletAddress:wallet,scope});const p=provider();if(!p)throw Error('Wallet connection is unavailable.');const signed=await p.signMessage(new TextEncoder().encode(c.message),'utf8');const sig=typeof signed==='string'?signed:(signed.signature?toBase58(signed.signature):toBase58(signed));return{signature:sig,message:c.message}}
async function connectWallet(){const p=provider();if(!p){message('Install Phantom or Solflare to continue.',true);return}try{const result=await p.connect();wallet=result.publicKey?.toString()||p.publicKey?.toString();if(!wallet)throw Error('Wallet did not return a public address.');$('walletAddress').textContent=short(wallet);$('walletButton').textContent='Sign in with wallet →';$('walletButton').dataset.action='sign';message('Wallet connected. Sign the secure login message to load your profile.')}catch(e){if(e?.code!==4001)message(e.message||'Wallet connection cancelled.',true)}}
function applyJourneyState(state){journeyState=state||{progress:[],traits:[]};const completed=journeyState.progress.filter(x=>x.status==='completed');document.querySelectorAll('[data-progress-count]').forEach(e=>e.textContent=completed.length)}
async function signInWallet(){if(!wallet)return connectWallet();const button=$('walletButton');button.disabled=true;button.textContent='Preparing secure sign-in…';try{const c=await signChallenge('login');button.textContent='Verifying signature…';const result=await api({action:'verify',walletAddress:wallet,signature:c.signature});profile=result.profile;applyJourneyState(result);localStorage.setItem('ud_wallet',wallet);renderDashboard(profile);showOnly(result.isNew?setupShell:dashboardShell);message(result.isNew?'Wallet verified. Create your Explorer.':`Welcome back, ${profile.username}! Your XP and learning progress have been restored.`)}catch(e){message(e.message||'Could not verify wallet signature.',true)}finally{button.disabled=false;button.textContent='Sign in with wallet →'}}
function toBase58(bytes){const A='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';let n=0n;for(const b of bytes)n=n*256n+BigInt(b);let s='';while(n){const r=Number(n%58n);s=A[r]+s;n/=58n}for(const b of bytes){if(b===0)s='1'+s;else break}return s||'1'}
$('walletButton')?.addEventListener('click',()=>($('walletButton').dataset.action==='sign'?signInWallet():connectWallet()));$('walletConnectSmall')?.addEventListener('click',connectWallet);
function renderCharacter(style){const el=$('characterHead');if(el)el.dataset.style=style||'Explorer';document.querySelectorAll('.character-option').forEach(x=>x.classList.toggle('selected',x.dataset.style===(style||'Explorer')))}
function levelName(level){return['Explorer','Wallet Keeper','Trader','Staker','DeFi Explorer','Protocol Scout','Builder','Solana Navigator','DeFi Master','Solana Sage'][Math.max(0,Math.min(9,(level||1)-1))]}
function evolution(level){const l=Math.max(1,Math.min(10,level||1));return Math.round(((l-1)/9)*100)}
async function loadTraits(){try{const{data}=await supabaseClient.from('traits').select('id,name,description,icon,rarity,required_level').order('required_level');return data||[]}catch{return[]}}
function injectJourneyUI(){if($('journeyUI'))return;const host=document.querySelector('.dash-content');if(!host)return;const wrap=document.createElement('div');wrap.id='journeyUI';wrap.innerHTML=`<section class="evolution-card"><div class="evolution-top"><div><p class="eyebrow">CHARACTER EVOLUTION</p><h3 class="evolution-title" id="evolutionName">Explorer</h3><p class="evolution-copy">Your character grows as your knowledge grows. Complete learning paths to unlock new traits and evolve through ten levels.</p></div><div class="dashboard-character" id="evolutionAvatar">◎</div></div><div class="evolution-meter"><span id="evolutionMeter"></span></div><div class="trait-pills" id="traitPills"></div></section><section class="lesson-card"><div><p class="eyebrow">NEXT MISSION</p><h3>Wallet Safety 101</h3><p>Learn the fundamentals of wallets, signing and protecting your keys. <b>+100 XP</b></p></div><button class="primary-button" id="startLesson">Start lesson <span>→</span></button></section>`;const saved=document.querySelector('.saved-profile');host.insertBefore(wrap,saved||null);$('startLesson')?.addEventListener('click',openFirstLesson)}
async function renderEvolution(p){injectJourneyUI();const level=p.current_level||1;$('evolutionName')&&($('evolutionName').textContent=`Level ${String(level).padStart(2,'0')} · ${levelName(level)}`);$('evolutionMeter')&&($('evolutionMeter').style.width=`${evolution(level)}%`);const icon=p.character_style==='Builder'?'⌘':p.character_style==='Trader'?'↗':p.character_style==='Guardian'?'◆':'◎';$('evolutionAvatar')&&($('evolutionAvatar').textContent=icon);const traits=await loadTraits();const pills=$('traitPills');if(pills)pills.innerHTML=traits.map(t=>`<span class="trait-pill ${level>=t.required_level?'':'locked'}">${t.icon||'✦'} ${t.name}${level<t.required_level?` · Lv ${t.required_level}`:''}</span>`).join('')}
function renderDashboard(p){profile=p;const name=p.username||'Explorer',style=p.character_style||'Explorer',goal=p.learning_goal||'Solana basics';document.querySelectorAll('#dashName,#savedName').forEach(e=>e.textContent=name);if($('welcomeName'))$('welcomeName').textContent=name;if($('savedExperience'))$('savedExperience').textContent=`${p.experience||'Complete beginner'} · ${style}`;if($('dashGoal'))$('dashGoal').textContent=goal;if($('goalStat'))$('goalStat').textContent=goal;document.querySelectorAll('#dashAvatar,#dashAvatarTop').forEach(e=>e.textContent=name.trim().charAt(0).toUpperCase());$('dashXp')&&($('dashXp').textContent=p.xp??0);$('dashStreak')&&($('dashStreak').textContent=p.streak??0);$('dashLevel')&&($('dashLevel').textContent=`${p.current_level||1} / 10`);$('dashboardCharacter')&&($('dashboardCharacter').textContent=style==='Builder'?'⌘':style==='Trader'?'↗':style==='Guardian'?'◆':'◎');$('dashWallet')&&($('dashWallet').textContent=short(wallet));applyJourneyState(journeyState);renderEvolution(p)}
document.querySelectorAll('.character-option').forEach(o=>o.addEventListener('click',()=>{document.querySelectorAll('.character-option').forEach(x=>x.classList.remove('selected'));o.classList.add('selected');renderCharacter(o.dataset.style)}));document.querySelectorAll('.goal').forEach(g=>g.addEventListener('click',()=>{document.querySelectorAll('.goal').forEach(x=>x.classList.remove('selected'));g.classList.add('selected')}));
$('profileForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!wallet)return;const button=e.target.querySelector('button[type="submit"]');button.disabled=true;button.textContent='Sign to save…';try{const c=await signChallenge('profile_update');const r=await api({action:'update_profile',walletAddress:wallet,signature:c.signature,username:$('name').value.trim()||'Explorer',experience:$('experience').value,learning_goal:document.querySelector('.goal.selected')?.dataset.goal||'Solana basics',character_style:document.querySelector('.character-option.selected')?.dataset.style||'Explorer'});profile=r.profile;applyJourneyState(r);renderDashboard(profile);showOnly(dashboardShell);message('Character saved securely. Your wallet now carries this profile across future sessions.')}catch(err){message(err.message||'Could not save profile.',true)}finally{button.disabled=false;button.innerHTML='Enter my journey <span>→</span>'}});
function lessonProgress(){return journeyState.progress.find(x=>x.lesson_id===FIRST_LESSON)}
function openFirstLesson(){const existing=lessonProgress();if(existing?.status==='completed'){message('Wallet Safety 101 is already complete. Your XP is safely saved.');return}if($('lessonModal')){$('lessonModal').classList.remove('hidden');return}const modal=document.createElement('div');modal.id='lessonModal';modal.className='lesson-modal';modal.innerHTML=`<div class="lesson-dialog"><button class="lesson-close" id="lessonClose">×</button><p class="eyebrow">SOLANA FOUNDATIONS · MISSION 01</p><h2>Wallet Safety 101</h2><p class="lesson-intro">Your wallet is your identity. Learn the one rule that protects it from the most common signing mistakes.</p><div class="lesson-callout"><span>🔐</span><div><b>Golden rule</b><p>Never share your seed phrase or private key — and never sign a transaction you don't understand.</p></div></div><h3>Knowledge check</h3><p>Someone asks you to enter your seed phrase into a website to “verify your wallet”. What should you do?</p><div class="lesson-answers"><button data-answer="wrong">Enter it if the website looks legitimate.</button><button data-answer="right">Never enter it. Close the site and keep the seed phrase offline.</button><button data-answer="wrong">Send the phrase only through a private message.</button></div><div class="lesson-result" id="lessonResult"></div></div>`;document.body.appendChild(modal);$('lessonClose').addEventListener('click',()=>modal.classList.add('hidden'));modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.add('hidden')});modal.querySelectorAll('.lesson-answers button').forEach(b=>b.addEventListener('click',()=>handleLessonAnswer(b.dataset.answer,b)))}
async function handleLessonAnswer(answer,button){const result=$('lessonResult');if(answer!=='right'){result.className='lesson-result wrong';result.textContent='Not quite. Your seed phrase should never be entered into a website. Try again.';return}document.querySelectorAll('.lesson-answers button').forEach(b=>b.disabled=true);result.className='lesson-result success';result.textContent='Correct. Secure answer verified. Saving +100 XP…';try{const c=await signChallenge('lesson_complete');const r=await api({action:'complete_lesson',walletAddress:wallet,signature:c.signature,lessonId:FIRST_LESSON});profile=r.profile;applyJourneyState(r);renderDashboard(profile);result.textContent=`Mission complete! +${r.xp_awarded??100} XP earned. Your progress is saved to your wallet.`;setTimeout(()=>{$('lessonModal')?.classList.add('hidden')},1800)}catch(e){result.className='lesson-result wrong';result.textContent=e.message||'Could not save the lesson. Nothing was awarded.';document.querySelectorAll('.lesson-answers button').forEach(b=>b.disabled=false)}}
async function logout(){const p=provider();try{await p?.disconnect?.()}catch{}wallet=null;profile=null;journeyState={progress:[],traits:[]};localStorage.removeItem('ud_wallet');showOnly(authShell);message('Wallet disconnected. Your profile, XP and learning progress remain safely stored in UnlockingDeFi.')}
$('signOut')?.addEventListener('click',logout);$('dashboardSignOut')?.addEventListener('click',logout);window.addEventListener('load',()=>{const remembered=localStorage.getItem('ud_wallet');if(remembered)$('walletAddress').textContent=short(remembered);showOnly(authShell)});