const SUPABASE_URL='https://dvpxlirjmyluwljivtdw.supabase.co';
const SUPABASE_KEY='sb_publishable_E4GiDJ-pJ5n2a0WGBpHOdQ_upqwyiCA';
const LIVE_URL='https://unlocking-de-fi.vercel.app/';
const supabaseClient=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=id=>document.getElementById(id),toast=$('toast'),authShell=$('authShell'),setupShell=$('setupShell'),dashboardShell=$('dashboardShell'),authStatus=$('authStatus'),resetModal=$('resetModal');
let authMode='signup',recoveryMode=false;
function message(text,error=false){if(authStatus){authStatus.textContent=text;authStatus.style.color=error?'#ff8f9c':'#bd91ff'}if(toast){toast.textContent=text;toast.classList.add('show');clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>toast.classList.remove('show'),3200)}}
function showOnly(section){[authShell,setupShell,dashboardShell].forEach(el=>el?.classList.add('hidden'));section?.classList.remove('hidden')}
function initials(name){return(name||'Explorer').trim().charAt(0).toUpperCase()}
async function loadUser(){if(!supabaseClient)return;const{data:{session}}=await supabaseClient.auth.getSession();if(!session){showOnly(authShell);return}const{data:profile,error}=await supabaseClient.from('profiles').select('*').eq('id',session.user.id).maybeSingle();if(error||!profile){showOnly(setupShell);return}renderDashboard(profile);showOnly(dashboardShell)}
function renderDashboard(profile){const name=profile.username||'Explorer',goal=profile.learning_goal||'Solana basics',style=profile.character_style||'Explorer';document.querySelectorAll('#dashName,#savedName').forEach(el=>el.textContent=name);if($('welcomeName'))$('welcomeName').textContent=name;if($('savedExperience'))$('savedExperience').textContent=`${profile.experience||'Complete beginner'} · ${style}`;if($('dashGoal'))$('dashGoal').textContent=goal;if($('goalStat'))$('goalStat').textContent=goal;document.querySelectorAll('#dashAvatar,#dashAvatarTop').forEach(el=>el.textContent=initials(name));const dc=$('dashboardCharacter');if(dc)dc.textContent=style==='Builder'?'⌘':style==='Trader'?'↗':style==='Guardian'?'◆':'◎';if($('dashXp'))$('dashXp').textContent=profile.xp??0;if($('dashStreak'))$('dashStreak').textContent=profile.streak??0;if($('dashLevel'))$('dashLevel').textContent=`${profile.current_level||1} / 10`}
document.querySelectorAll('.auth-tab').forEach(tab=>tab.addEventListener('click',()=>{if(recoveryMode)return;authMode=tab.dataset.mode;document.querySelectorAll('.auth-tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');const signup=authMode==='signup';$('authTitle').textContent=signup?'Start your journey.':'Welcome back.';$('authCopy').textContent=signup?'Create an account and keep your learning progress wherever you go.':'Log in to pick up exactly where you left off.';$('authSubmit').innerHTML=signup?'Create account <span>→</span>':'Log in <span>→</span>';$('password').autocomplete=signup?'new-password':'current-password';if(authStatus)authStatus.textContent=''}));
$('authForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!supabaseClient)return message('Authentication is unavailable right now.',true);const email=$('email').value.trim(),password=$('password').value,submit=$('authSubmit');submit.disabled=true;submit.textContent=authMode==='signup'?'Creating account…':'Logging in…';if(authMode==='signup'){const{data,error}=await supabaseClient.auth.signUp({email,password,options:{emailRedirectTo:LIVE_URL}});if(error)message(error.message,true);else if(data.session){message('Account created. Let’s build your profile.');showOnly(setupShell)}else message('If this email is new, check your inbox to confirm. If you already have an account, use Log in or Forgot your password.')}else{const{data,error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)message(error.message,true);else{message('Welcome back!');await loadUser()}}submit.disabled=false;submit.innerHTML=authMode==='signup'?'Create account <span>→</span>':'Log in <span>→</span>'});
$('forgotPassword')?.addEventListener('click',()=>{recoveryMode=true;resetModal?.classList.remove('hidden');const email=$('email')?.value.trim();if(email)$('resetEmail').value=email});$('closeReset')?.addEventListener('click',()=>{recoveryMode=false;resetModal?.classList.add('hidden')});
$('resetForm')?.addEventListener('submit',async e=>{e.preventDefault();const email=$('resetEmail').value.trim(),button=$('resetSubmit');button.disabled=true;button.textContent='Sending…';const{error}=await supabaseClient.auth.resetPasswordForEmail(email,{redirectTo:LIVE_URL});if(error)message(error.message,true);else{resetModal.classList.add('hidden');recoveryMode=false;message('If an account exists for that email, a secure reset link has been sent. Check your inbox.')}button.disabled=false;button.innerHTML='Send reset link <span>→</span>'});
document.querySelectorAll('.character-option').forEach(option=>option.addEventListener('click',()=>{document.querySelectorAll('.character-option').forEach(o=>o.classList.remove('selected'));option.classList.add('selected');const head=$('characterHead');if(head)head.dataset.style=option.dataset.style}));document.querySelectorAll('.goal').forEach(goal=>goal.addEventListener('click',()=>{document.querySelectorAll('.goal').forEach(g=>g.classList.remove('selected'));goal.classList.add('selected')}));
$('profileForm')?.addEventListener('submit',async e=>{e.preventDefault();const{data:{user}}=await supabaseClient.auth.getUser();if(!user){showOnly(authShell);return}const username=$('name').value.trim()||'Explorer',experience=$('experience').value,learning_goal=document.querySelector('.goal.selected')?.dataset.goal||'Solana basics',character_style=document.querySelector('.character-option.selected')?.dataset.style||'Explorer',button=e.target.querySelector('button[type="submit"]');button.disabled=true;button.textContent='Saving…';const{data:profile,error}=await supabaseClient.from('profiles').upsert({id:user.id,username,experience,learning_goal,character_style},{onConflict:'id'}).select().single();if(error){message('Profile could not be saved yet.',true);button.disabled=false;button.innerHTML='Enter my journey <span>→</span>';return}renderDashboard(profile);showOnly(dashboardShell);message(`Welcome to UnlockingDeFi, ${username}!`);button.disabled=false;button.innerHTML='Enter my journey <span>→</span>'});
async function signOut(){await supabaseClient?.auth.signOut();showOnly(authShell);message('You have been signed out.')}$('signOut')?.addEventListener('click',signOut);$('dashboardSignOut')?.addEventListener('click',signOut);
supabaseClient?.auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY'){recoveryMode=true;showOnly(authShell);resetModal?.classList.remove('hidden');const card=resetModal?.querySelector('.reset-card');if(card){card.querySelector('.eyebrow').textContent='PASSWORD RESET';card.querySelector('h2').textContent='Choose a new password.';card.querySelector('p:not(.eyebrow)').textContent='Enter and confirm your new password.';const form=card.querySelector('form');form.innerHTML='<label>New password<input id="newPassword" type="password" minlength="6" autocomplete="new-password" placeholder="At least 6 characters" required></label><label>Confirm password<input id="confirmPassword" type="password" minlength="6" autocomplete="new-password" placeholder="Repeat your password" required></label><button class="primary-button full" type="submit" id="newPasswordSubmit">Update password <span>→</span></button>';form.onsubmit=async ev=>{ev.preventDefault();const p=$('newPassword').value,c=$('confirmPassword').value;if(p!==c){message('Passwords do not match.',true);return}const b=$('newPasswordSubmit');b.disabled=true;b.textContent='Updating…';const{error}=await supabaseClient.auth.updateUser({password:p});if(error){message(error.message,true);b.disabled=false;b.innerHTML='Update password <span>→</span>'}else{recoveryMode=false;resetModal.classList.add('hidden');message('Password updated successfully.');await loadUser()}}}}else if(event==='SIGNED_OUT')showOnly(authShell)});loadUser();