const LESSON_API_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2cHhsaXJqbXlsdXdsaml2dGR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYyNzQxOTMsImV4cCI6MjEwMTg1MDE5M30.GmGpjRq4TE6RDfOThQG94ww2jFr0_JPQ_60ADUu_bwg';
const LESSON_PATH='db6e6aa3-5c2b-4663-8dd8-4068aa29720f';
let udLessons=[];
async function loadLessons(){const r=await fetch(`${SUPABASE_URL}/rest/v1/lessons?path_id=eq.${LESSON_PATH}&published=eq.true&select=id,slug,title,description,xp_reward,sort_order,content&order=sort_order.asc`,{headers:{apikey:LESSON_API_KEY,Authorization:`Bearer ${LESSON_API_KEY}`}});if(!r.ok)throw Error('Could not load lessons');udLessons=await r.json();return udLessons}
function completedLesson(id){return journeyState.progress.some(x=>x.lesson_id===id&&x.status==='completed')}
function lessonUnlocked(i){return i===0||completedLesson(udLessons[i-1]?.id)}
function injectJourneyUI(){if($('journeyUI'))return;const host=document.querySelector('.dash-content');if(!host)return;const wrap=document.createElement('div');wrap.id='journeyUI';wrap.innerHTML=`<section class="evolution-card"><div class="evolution-top"><div><p class="eyebrow">CHARACTER EVOLUTION</p><h3 class="evolution-title" id="evolutionName">Explorer</h3><p class="evolution-copy">Learn, earn XP and evolve your Gecko. Every completed mission moves your journey forward.</p></div><div class="dashboard-character" id="evolutionAvatar">◎</div></div><div class="evolution-meter"><span id="evolutionMeter"></span></div><div class="trait-pills" id="traitPills"></div></section><section class="missions-section"><div class="missions-heading"><div><p class="eyebrow">SOLANA FOUNDATIONS</p><h3>Your missions</h3></div><span id="missionCount">0 / 5 complete</span></div><div class="mission-grid" id="missionGrid"><div class="mission-loading">Loading your learning journey…</div></div></section>`;const saved=document.querySelector('.saved-profile');host.insertBefore(wrap,saved||null);renderMissionList().catch(()=>{const g=$('missionGrid');if(g)g.innerHTML='<div class="mission-loading">Could not load missions. Refresh and try again.</div>'})}
async function renderMissionList(){const grid=$('missionGrid');if(!grid)return;try{await loadLessons()}catch(e){grid.innerHTML='<div class="mission-loading">Could not load missions. Refresh and try again.</div>';return}const done=udLessons.filter(l=>completedLesson(l.id)).length;if($('missionCount'))$('missionCount').textContent=`${done} / ${udLessons.length} complete`;grid.innerHTML=udLessons.map((l,i)=>{const doneNow=completedLesson(l.id),unlocked=lessonUnlocked(i),num=String(i+1).padStart(2,'0');return `<article class="mission-card ${doneNow?'complete':''} ${!unlocked?'locked':''}"><div class="mission-number">${doneNow?'✓':num}</div><div class="mission-copy"><p class="eyebrow">MISSION ${num} · ${l.xp_reward} XP</p><h4>${l.title}</h4><p>${l.description||''}</p></div><button class="mission-button" data-lesson="${l.id}" ${!unlocked||doneNow?'disabled':''}>${doneNow?'Completed ✓':unlocked?'Start mission →':'Locked 🔒'}</button></article>`}).join('');grid.querySelectorAll('[data-lesson]').forEach(b=>b.addEventListener('click',()=>openLesson(b.dataset.lesson)))}
function renderDashboard(p){profile=p;const name=p.username||'Explorer',style=p.character_style||'Explorer',goal=p.learning_goal||'Solana basics';document.querySelectorAll('#dashName,#savedName').forEach(e=>e.textContent=name);if($('welcomeName'))$('welcomeName').textContent=name;if($('savedExperience'))$('savedExperience').textContent=`${p.experience||'Complete beginner'} · ${style}`;if($('dashGoal'))$('dashGoal').textContent=goal;if($('goalStat'))$('goalStat').textContent=goal;document.querySelectorAll('#dashAvatar,#dashAvatarTop').forEach(e=>e.textContent=name.trim().charAt(0).toUpperCase());$('dashXp')&&($('dashXp').textContent=p.xp??0);$('dashStreak')&&($('dashStreak').textContent=p.streak??0);$('dashLevel')&&($('dashLevel').textContent=`${p.current_level||1} / 10`);$('dashboardCharacter')&&($('dashboardCharacter').textContent=style==='Builder'?'⌘':style==='Trader'?'↗':style==='Guardian'?'◆':'◎');$('dashWallet')&&($('dashWallet').textContent=short(wallet));applyJourneyState(journeyState);renderEvolution(p);setTimeout(()=>renderMissionList(),50)}
function openFirstLesson(){if(!udLessons.length){loadLessons().then(()=>openLesson(udLessons[0]?.id)).catch(()=>message('Could not load your lessons.',true));return}openLesson(udLessons[0]?.id)}
let activeLesson=null,activeQuestion=0,lessonScore=0;
function openLesson(id){const lesson=udLessons.find(x=>x.id===id);if(!lesson)return message('Lesson unavailable.',true);const index=udLessons.findIndex(x=>x.id===id);if(!lessonUnlocked(index))return message('Complete the previous mission first.',true);if(completedLesson(id))return message('Mission already complete. Your XP is safely saved.');activeLesson=lesson;activeQuestion=0;lessonScore=0;let modal=$('lessonModal');if(!modal){modal=document.createElement('div');modal.id='lessonModal';modal.className='lesson-modal';document.body.appendChild(modal)}modal.classList.remove('hidden');renderQuestion();}
function renderQuestion(){const modal=$('lessonModal'),qs=activeLesson.content?.questions||[];if(!modal||!activeLesson)return;const q=qs[activeQuestion];const total=qs.length;modal.innerHTML=`<div class="lesson-dialog"><button class="lesson-close" id="lessonClose">×</button><p class="eyebrow">SOLANA FOUNDATIONS · MISSION ${String(activeLesson.sort_order).padStart(2,'0')}</p><div class="lesson-progress-label">QUESTION ${activeQuestion+1} / ${total}</div><div class="lesson-progress-bar"><span style="width:${Math.round((activeQuestion/total)*100)}%"></span></div><h2>${activeLesson.title}</h2><p class="lesson-intro">${activeQuestion===0?(activeLesson.content?.intro||'Learn the concept, then prove your knowledge.'):'Keep going — you are building your Solana knowledge.'}</p><div class="lesson-question"><h3>${q.question}</h3><div class="lesson-answers">${q.answers.map((a,i)=>`<button data-answer="${i}">${a}</button>`).join('')}</div><div class="lesson-result" id="lessonResult"></div></div></div>`;$('lessonClose').addEventListener('click',()=>modal.classList.add('hidden'));modal.querySelectorAll('.lesson-answers button').forEach(b=>b.addEventListener('click',()=>answerQuestion(Number(b.dataset.answer),b)));}
function answerQuestion(choice,button){const q=activeLesson.content.questions[activeQuestion],result=$('lessonResult');if(choice!==q.correct){result.className='lesson-result wrong';result.innerHTML=`Not quite. ${q.explanation||'Review the concept and try again.'}`;return}lessonScore++;document.querySelectorAll('.lesson-answers button').forEach(b=>b.disabled=true);result.className='lesson-result success';result.textContent=activeQuestion+1<activeLesson.content.questions.length?'Correct! Next question →':'Correct! Lesson complete →';setTimeout(()=>{if(activeQuestion+1<activeLesson.content.questions.length){activeQuestion++;renderQuestion()}else finishLesson()},650)}
async function finishLesson(){const result=$('lessonResult');if(result)result.textContent=`All ${activeLesson.content.questions.length} questions correct. Sign once to save +${activeLesson.xp_reward} XP.`;const buttons=document.querySelectorAll('.lesson-answers button');buttons.forEach(b=>b.disabled=true);try{const c=await signChallenge('lesson_complete');const r=await api({action:'complete_lesson',walletAddress:wallet,signature:c.signature,lessonId:activeLesson.id});profile=r.profile;applyJourneyState(r);renderDashboard(profile);const doneMsg=$('lessonResult');if(doneMsg)doneMsg.textContent=`Mission complete! +${r.xp_awarded??activeLesson.xp_reward} XP earned. Saved to your wallet.`;setTimeout(()=>{$('lessonModal')?.classList.add('hidden')},1600)}catch(e){if(result){result.className='lesson-result wrong';result.textContent=e.message||'Could not save the lesson. Nothing was awarded.'}buttons.forEach(b=>b.disabled=false)}}
